echo
ARG="./philo 0 0 0 0"; echo "Test 1: $ARG"; valgrind --leak-check=full $ARG 2> /dev/null && echo "Failed" || echo "Check!"
echo "========================================================================="
ARG="./philo 1 0 0 0"; echo "Test 2: $ARG"; valgrind --leak-check=full $ARG >/dev/null && echo "Check!" || echo "Failed!"
echo "========================================================================="
ARG="./philo 1 1000 1000 1000"; echo "Test 3: $ARG"; valgrind --leak-check=full $ARG >/dev/null && echo "Check!" || echo "Failed!"
echo "========================================================================="
ARG="./philo 5 1000 1000 1000"; echo "Test 4: $ARG"; valgrind --leak-check=full $ARG >/dev/null && echo "Check!" || echo "Failed!"
echo "========================================================================="
ARG="./philo 200 1000 1000 1000"; echo "Test 5: $ARG"; valgrind --leak-check=full $ARG >/dev/null && echo "Check!" || echo "Failed!"
echo "========================================================================="
